 ###
GET http://localhost:8000/booking


### create a client
POST http://localhost:8000/booking HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ablo", 
    "lastName": " Kouma", 
    "email": "ablok01@gmail.com",
    "city": "Abuja", 
    "country": "Nigeria",
    "user_profile_id": "234",
    "vehicle_id": "342345",
    "discount_id": "23",
    "discount_type": "cash",
    "discount": "334"
}