 ###
GET http://localhost:8000/booking


### create a client
POST http://localhost:8000/booking HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ablo", 
    "lastName": " Kouma", 
    "email": "ablok01@gmail.com",
    "city": "Abuja", 
    "country": "Nigeria",
    "user_profile_id": "234",
    "vehicle_id": "342345",
    "discount_id": "23",
    "discount_type": "cash",
    "discount": "334"
}

### update client
PUT http://localhost:8000/booking/62896b444638c1511096b337 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Edmond", 
    "lastName": "Alok", 
    "email": "edmondallu01@gmail.com",
    "city": "Lome", 
    "country": "14/03/1997",
    "user_profile_id": "3445",
    "vehicle_id": "34223",
    "discount_id": "22",
    "discount_type": "cash",
    "discount": "33333"
}

### delete client
DELETE http://localhost:8000/booking/62896dcd5d60769edf3172c1
